### PR TITLE
Test framework

### PR DESCRIPTION
**Pull request by themikejr**
This PR does the following:

* introduces the pytest framework
* adds base unit test suite for nodes, lowfat, and tsv
* a github action that will prevent pull requests from being merged if the tests fail

### CODE REVIEW

**Comment by themikejr** [comment]
There are currently two failing tests that ironically prevent this from being merged:

1. number of words in `lowfat`
2. number of words in `macula_hebrew.tsv`

**Comment by jacobwegner** [comment]
@themikejr wrote:

> There are currently two failing tests that ironically prevent this from being merged:
> 
> 1. number of words in `lowfat`
> 2. number of words in `macula_hebrew.tsv`

Given that the missing words are a known issue (https://github.com/Clear-Bible/symphony-team/issues/207), I would suggest we either:

1) Update the expected word counts to match what is actually in the lowfat / TSVs (and then the "fix" for #207 would include updating the tests so they pass again with the new counts)
2) Mark them using the [xfail marker](https://docs.pytest.org/en/7.1.x/how-to/skipping.html?highlight=xfail#xfail-mark-test-functions-as-expected-to-fail); when we resolve #207, we can remove the marker

**Comment by themikejr** [comment]
> @themikejr wrote:
> 
> > There are currently two failing tests that ironically prevent this from being merged:
> > 
> > 1. number of words in `lowfat`
> > 2. number of words in `macula_hebrew.tsv`
> 
> Given that the missing words are a known issue ([Clear-Bible/symphony-team#207](https://github.com/Clear-Bible/symphony-team/issues/207)), I would suggest we either:
> 
> 1. Update the expected word counts to match what is actually in the lowfat / TSVs (and then the "fix" for #207 would include updating the tests so they pass again with the new counts)
> 2. Mark them using the [xfail marker](https://docs.pytest.org/en/7.1.x/how-to/skipping.html?highlight=xfail#xfail-mark-test-functions-as-expected-to-fail); when we resolve #207, we can remove the marker

Thanks for the suggestions @jacobwegner. I went with the latter so that we don't lose the encoded expectation of the correct number of words.

**Comment by themikejr** [comment]
I believe this is ready for review now.

**Review by jacobwegner — APPROVED** [review]
LGTM @themikejr 

I tried to capture our conversation about optimizing tests vs. optimizing useful errors in https://github.com/Clear-Bible/symphony-team/issues/97#issuecomment-1281324104.

**Comment by jacobwegner** [comment]
(I'm going to go ahead and merge this in because it will be useful to have in place for https://github.com/Clear-Bible/symphony-team/issues/193)

**Pull request merged**
